enableSecurityManager: false # Not needed when running the standalone application
enableInputThread: true # To make "gradle run" work properly
contentMd5: true
cache:
  cachedFilesExpiry: 86400
  cachedAccountsMaxItems: 1000
  cachedIncludesExpiry: 3600
  cachedIncludesMaxItems: 1000
  cachedAccountIdsExpiry: 86400
  cachedBodiesMaxItems: 1000
  cachedAccountsExpiry: 1800
  cachedFilesMaxItems: 1000
  cachedSessionsMaxItems: 1000
  cachedAccountIdsMaxItems: 1000
  cachedBodiesExpiry: 3600
  enabled: false # Enable during runtime!
sessions:
  enableDb: true
  autoLoad: true
  sessionTimeout: 86400
debug: true
webAddress: kvantum.xyz
templates:
  engine: !!com.github.intellectualsites.kvantum.api.config.CoreConfig$TemplatingEngine 'VELOCITY'
  applyTemplates:
  - std
logPrefix: Foton
gzip: true
ssl:
  port: 443
  keyStorePassword: password
  enable: false
  keyStore: keyStore
verbose: true
hostname: kvantum.xyz
enableSyntax: true
application:
  databaseImplementation: sqlite
  main: ''
port: 80
buffer:
  in: 1048576
  out: 1048576
mongodb:
  dbMorphia: isites
  collectionSessions: sessions
  dbSessions: isites
  uri: mongodb://localhost:27017
  enabled: false
workers: 1
limits:
  limitRequestLines: 100
  limitRequestLineSize: 8190
disableViews: false
exitOnStop: true
