views:
  scripts:
    filter: assets/[file=index].js
    options:
      filePattern: ${file}.js
      folder: ./public/scripts
    type: javascript
  std:
    filter: '[file=index].[extension=html]'
    options:
      filePattern: ${file}.${extension}
      folder: ./public
      excludeExtensions:
      - txt
      - js
      extensionRewrite:
        html: vm
    type: std
