views:
  std:
    filter: '[file=index].[extension=html]'
    options:
      filePattern: ${file}.${extension}
      folder: ./public
      excludeExtensions:
      - txt
      extensionRewrite:
        html: vm
    type: std
